/*
Cara menggunakan:
1. Buka https://pluang.com/crypto-currency/trading-view-chart?cryptoCurrencySymbol=BTC&theme=light
2. Setting chart
3. Copy paste kode di bawah ini ke Console [Ctrl Shift I]
*/

document.title = 'Ctrl + Shift Kanan';

var listCoin = [
    'AAVEIDR',
    'AEVOIDR',
    'ELFIDR',
    'ALGOIDR',
    'ARKIDR',
    'ASTRIDR',
    'AVAXIDR',
    'BALIDR',
    'BATIDR',
    'QIIDR',
    'BNBIDR',
    'BTCIDR',
    'BLURIDR',
    'ADAIDR',
    'TIAIDR',
    'LINKIDR',
    'COMPIDR',
    'ATOMIDR',
    'COTIIDR',
    'CRVIDR',
    'CYBERIDR',
    'MANAIDR',
    'DOGEIDR',
    'WIFIDR',
    'ENJIDR',
    'EOSIDR',
    'ETHIDR',
    'FILIDR',
    'FTMIDR',
    'ONEIDR',
    'KSMIDR',
    'LTCIDR',
    'MKRIDR',
    'MEMEIDR',
    'XNOIDR',
    'NEOIDR',
    'CAKEIDR',
    'DOTIDR',
    'MATICIDR',
    'XRPIDR',
    'XLMIDR',
    'SOLIDR',
    'SUSHIIDR',
    'SXPIDR',
    'SNXIDR',
    'LUNAIDR',
    'LUNCIDR',
    'XTZIDR',
    'GRTIDR',
    'SANDIDR',
    'THETAIDR',
    'TRXIDR',
    'UNIIDR',
    'USDTIDR',
    'VETIDR',
    'YFIIDR',
    'GHSTIDR',
    'ACMIDR',
    'AGLDIDR',
    'ACHIDR',
    'TLMIDR',
    'ALPACAIDR',
    'ALPHAIDR',
    'ALPINEIDR',
    'ALTIDR',
    'ATMIDR',
    'ASRIDR',
    'AMPIDR',
    'ANCIDR',
    'ANKRIDR',
    'API3IDR',
    'APEIDR',
    'ANTIDR',
    'ARBIDR',
    'ARPAIDR',
    'ARIDR',
    'AUDIOIDR',
    'AXLIDR',
    'AXSIDR',
    'BAKEIDR',
    'BANDIDR',
    'BNTIDR',
    'BONDIDR',
    'BEAMXIDR',
    'BELIDR',
    'BICOIDR',
    'BNXIDR',
    'BUSDIDR',
    'BSWIDR',
    'BCHIDR',
    'BTTCIDR',
    'BONKIDR',
    'CTSIIDR',
    'CELOIDR',
    'CELRIDR',
    'CHZIDR',
    'CHRIDR',
    'CVCIDR',
    'COCOSIDR',
    'C98IDR',
    'COMBOIDR',
    'CFXIDR',
    'PEOPLEIDR',
    'CVXIDR',
    'CREAMIDR',
    'DASHIDR',
    'DEPIDR',
    'DENTIDR',
    'YFIIIDR',
    'DUSKIDR',
    'DYDXIDR',
    'DYMIDR',
    'XECIDR',
    'MLNIDR',
    'EGLDIDR',
    'ETCIDR',
    'ENSIDR',
    'ERNIDR',
    'PORTOIDR',
    'BARIDR',
    'FLMIDR',
    'FLOKIIDR',
    'FLOWIDR',
    'FLUXIDR',
    'FTTIDR',
    'FXSIDR',
    'ACEIDR',
    'GALAIDR',
    'GALIDR',
    'GNSIDR',
    'GASIDR',
    'GMXIDR',
    'GFTIDR',
    'HFTIDR',
    'HBARIDR',
    'HNTIDR',
    'HIGHIDR',
    'HIFIIDR',
    'HIVEIDR',
    'HOTIDR',
    'ZENIDR',
    'ICXIDR',
    'RLCIDR',
    'ILVIDR',
    'IMXIDR',
    'ICPIDR',
    'INJIDR',
    'IOSTIDR',
    'IQIDR',
    'IOTXIDR',
    'MIOTAIDR',
    'JASMYIDR',
    'JSTIDR',
    'JTOIDR',
    'JUPIDR',
    'JUVIDR',
    'KDAIDR',
    'KAVAIDR',
    'KLAYIDR',
    'KNCIDR',
    'LOKAIDR',
    'LEVERIDR',
    'LDOIDR',
    'LITIDR',
    'LPTIDR',
    'LRCIDR',
    'LOOMIDR',
    'CITYIDR',
    'MANTAIDR',
    'OMIDR',
    'METISIDR',
    'MDXIDR',
    'MTLIDR',
    'MINAIDR',
    'DARIDR',
    'MBOXIDR',
    'XMRIDR',
    'GLMRIDR',
    'MOVRIDR',
    'MBLIDR',
    'MULTIIDR',
    'ALICEIDR',
    'NEARIDR',
    'NTRNIDR',
    'XEMIDR',
    'CKBIDR',
    'NEXOIDR',
    'NFPIDR',
    'NKNIDR',
    'NMRIDR',
    'ROSEIDR',
    'OCEANIDR',
    'OGIDR',
    'OMGIDR',
    '1INCHIDR',
    'ONTIDR',
    'OOKIIDR',
    'OPIDR',
    'OGNIDR',
    'OXTIDR',
    'ORDIIDR',
    'PSGIDR',
    'USDPIDR',
    'PERPIDR',
    'PLAIDR',
    'PIXELIDR',
    'PDAIDR',
    'PEPEIDR',
    'POLSIDR',
    'POLYXIDR',
    'PORTALIDR',
    'POWRIDR',
    'PROMIDR',
    'PYTHIDR',
    'QTUMIDR',
    'QNTIDR',
    'RADIDR',
    'RVNIDR',
    'RAYIDR',
    'REEFIDR',
    'REIIDR',
    'RENIDR',
    'RNDRIDR',
    'REQIDR',
    'RSRIDR',
    'RONINIDR',
    '1000SATSIDR',
    'SRMIDR',
    'SHIBIDR',
    'SCIDR',
    'AIIDR',
    'SLPIDR',
    'SPELLIDR',
    'LAZIOIDR',
    'SSVIDR',
    'SANTOSIDR',
    'SEIIDR',
    'CTKIDR',
    'STXIDR',
    'STPTIDR',
    'STGIDR',
    'STRKIDR',
    'GMTIDR',
    'STORJIDR',
    'STMXIDR',
    'STRAXIDR',
    'DATAIDR',
    'SUIIDR',
    'SUPERIDR',
    'SYSIDR',
    'USTCIDR',
    'TVKIDR',
    'TRBIDR',
    'TFUELIDR',
    'RUNEIDR',
    'TOMOIDR',
    'TWTIDR',
    'UMAIDR',
    'UNFIIDR',
    'USDCIDR',
    'VANRYIDR',
    'VELOIDR',
    'XVSIDR',
    'VRAIDR',
    'VTHOIDR',
    'VICIDR',
    'VOXELIDR',
    'VGXIDR',
    'PYRIDR',
    'WAVESIDR',
    'WAXPIDR',
    'WRXIDR',
    'WINIDR',
    'WOOIDR',
    'WLDIDR',
    'XAIIDR',
    'YGGIDR',
    'ZECIDR',
    'ZRXIDR',
    'ZILIDR'
];

function acak(array) {
    var currentIndex = array.length, temporaryValue, randomIndex;

    // While there remain elements to shuffle...
    while (0 !== currentIndex) {

        // Pick a remaining element...
        randomIndex = Math.floor(Math.random() * currentIndex);
        currentIndex -= 1;

        // And swap it with the current element.
        temporaryValue = array[currentIndex];
        array[currentIndex] = array[randomIndex];
        array[randomIndex] = temporaryValue;
    }

    return array;
}

function sleep(n) {
    return new Promise(resolve => setTimeout(resolve, n));
}

document.querySelector('iframe').contentWindow.addEventListener('keydown', async (x) => {
    if (x.code == 'ShiftRight' && x.ctrlKey) {
        var iframe = document.querySelector('iframe').contentWindow;
        iframe.document.querySelector('#header-toolbar-symbol-search').click();
        await sleep(500);
        var pencarian = iframe.document.querySelector('[data-role="search"]');
        pencarian.value = acak(listCoin)[0];
    }
});
