
var listCoin = [
    'AAVEUSDT',
    'AEVOUSDT',
    'ELFUSDT',
    'ALGOUSDT',
    'ARKUSDT',
    'ASTRUSDT',
    'AVAXUSDT',
    'BALUSDT',
    'BATUSDT',
    'QIUSDT',
    'BNBUSDT',
    'BTCUSDT',
    'BLURUSDT',
    'ADAUSDT',
    'TIAUSDT',
    'LINKUSDT',
    'COMPUSDT',
    'ATOMUSDT',
    'COTIUSDT',
    'CRVUSDT',
    'CYBERUSDT',
    'MANAUSDT',
    'DOGEUSDT',
    'WIFUSDT',
    'ENJUSDT',
    'EOSUSDT',
    'ETHUSDT',
    'FILUSDT',
    'FTMUSDT',
    'ONEUSDT',
    'KSMUSDT',
    'LTCUSDT',
    'MKRUSDT',
    'MEMEUSDT',
    'XNOUSDT',
    'NEOUSDT',
    'CAKEUSDT',
    'DOTUSDT',
    'MATICUSDT',
    'XRPUSDT',
    'XLMUSDT',
    'SOLUSDT',
    'SUSHIUSDT',
    'SXPUSDT',
    'SNXUSDT',
    'LUNAUSDT',
    'LUNCUSDT',
    'XTZUSDT',
    'GRTUSDT',
    'SANDUSDT',
    'THETAUSDT',
    'TRXUSDT',
    'UNIUSDT',
    'VETUSDT',
    'YFIUSDT',
    'GHSTUSDT',
    'ACMUSDT',
    'AGLDUSDT',
    'ACHUSDT',
    'TLMUSDT',
    'ALPACAUSDT',
    'ALPHAUSDT',
    'ALPINEUSDT',
    'ALTUSDT',
    'ATMUSDT',
    'ASRUSDT',
    'AMPUSDT',
    'ANCUSDT',
    'ANKRUSDT',
    'API3USDT',
    'APEUSDT',
    'ANTUSDT',
    'ARBUSDT',
    'ARPAUSDT',
    'ARUSDT',
    'AUDIOUSDT',
    'AXLUSDT',
    'AXSUSDT',
    'BAKEUSDT',
    'BANDUSDT',
    'BNTUSDT',
    'BONDUSDT',
    'BEAMXUSDT',
    'BELUSDT',
    'BICOUSDT',
    'BNXUSDT',
    'BUSDUSDT',
    'BSWUSDT',
    'BCHUSDT',
    'BTTCUSDT',
    'BONKUSDT',
    'CTSIUSDT',
    'CELOUSDT',
    'CELRUSDT',
    'CHZUSDT',
    'CHRUSDT',
    'CVCUSDT',
    'COCOSUSDT',
    'C98USDT',
    'COMBOUSDT',
    'CFXUSDT',
    'PEOPLEUSDT',
    'CVXUSDT',
    'CREAMUSDT',
    'DASHUSDT',
    'DEPUSDT',
    'DENTUSDT',
    'YFIIUSDT',
    'DUSKUSDT',
    'DYDXUSDT',
    'DYMUSDT',
    'XECUSDT',
    'MLNUSDT',
    'EGLDUSDT',
    'ETCUSDT',
    'ENSUSDT',
    'ERNUSDT',
    'PORTOUSDT',
    'BARUSDT',
    'FLMUSDT',
    'FLOKIUSDT',
    'FLOWUSDT',
    'FLUXUSDT',
    'FTTUSDT',
    'FXSUSDT',
    'ACEUSDT',
    'GALAUSDT',
    'GALUSDT',
    'GNSUSDT',
    'GASUSDT',
    'GMXUSDT',
    'GFTUSDT',
    'HFTUSDT',
    'HBARUSDT',
    'HNTUSDT',
    'HIGHUSDT',
    'HIFIUSDT',
    'HIVEUSDT',
    'HOTUSDT',
    'ZENUSDT',
    'ICXUSDT',
    'RLCUSDT',
    'ILVUSDT',
    'IMXUSDT',
    'ICPUSDT',
    'INJUSDT',
    'IOSTUSDT',
    'IQUSDT',
    'IOTXUSDT',
    'MIOTAUSDT',
    'JASMYUSDT',
    'JSTUSDT',
    'JTOUSDT',
    'JUPUSDT',
    'JUVUSDT',
    'KDAUSDT',
    'KAVAUSDT',
    'KLAYUSDT',
    'KNCUSDT',
    'LOKAUSDT',
    'LEVERUSDT',
    'LDOUSDT',
    'LITUSDT',
    'LPTUSDT',
    'LRCUSDT',
    'LOOMUSDT',
    'CITYUSDT',
    'MANTAUSDT',
    'OMUSDT',
    'METISUSDT',
    'MDXUSDT',
    'MTLUSDT',
    'MINAUSDT',
    'DARUSDT',
    'MBOXUSDT',
    'XMRUSDT',
    'GLMRUSDT',
    'MOVRUSDT',
    'MBLUSDT',
    'MULTIUSDT',
    'ALICEUSDT',
    'NEARUSDT',
    'NTRNUSDT',
    'XEMUSDT',
    'CKBUSDT',
    'NEXOUSDT',
    'NFPUSDT',
    'NKNUSDT',
    'NMRUSDT',
    'ROSEUSDT',
    'OCEANUSDT',
    'OGUSDT',
    'OMGUSDT',
    '1INCHUSDT',
    'ONTUSDT',
    'OOKIUSDT',
    'OPUSDT',
    'OGNUSDT',
    'OXTUSDT',
    'ORDIUSDT',
    'PSGUSDT',
    'USDPUSDT',
    'PERPUSDT',
    'PLAUSDT',
    'PIXELUSDT',
    'PDAUSDT',
    'PEPEUSDT',
    'POLSUSDT',
    'POLYXUSDT',
    'PORTALUSDT',
    'POWRUSDT',
    'PROMUSDT',
    'PYTHUSDT',
    'QTUMUSDT',
    'QNTUSDT',
    'RADUSDT',
    'RVNUSDT',
    'RAYUSDT',
    'REEFUSDT',
    'REIUSDT',
    'RENUSDT',
    'RNDRUSDT',
    'REQUSDT',
    'RSRUSDT',
    'RONINUSDT',
    '1000SATSUSDT',
    'SRMUSDT',
    'SHIBUSDT',
    'SCUSDT',
    'AIUSDT',
    'SLPUSDT',
    'SPELLUSDT',
    'LAZIOUSDT',
    'SSVUSDT',
    'SANTOSUSDT',
    'SEIUSDT',
    'CTKUSDT',
    'STXUSDT',
    'STPTUSDT',
    'STGUSDT',
    'STRKUSDT',
    'GMTUSDT',
    'STORJUSDT',
    'STMXUSDT',
    'STRAXUSDT',
    'DATAUSDT',
    'SUIUSDT',
    'SUPERUSDT',
    'SYSUSDT',
    'USTCUSDT',
    'TVKUSDT',
    'TRBUSDT',
    'TFUELUSDT',
    'RUNEUSDT',
    'TOMOUSDT',
    'TWTUSDT',
    'UMAUSDT',
    'UNFIUSDT',
    'USDCUSDT',
    'VANRYUSDT',
    'VELOUSDT',
    'XVSUSDT',
    'VRAUSDT',
    'VTHOUSDT',
    'VICUSDT',
    'VOXELUSDT',
    'VGXUSDT',
    'PYRUSDT',
    'WAVESUSDT',
    'WAXPUSDT',
    'WRXUSDT',
    'WINUSDT',
    'WOOUSDT',
    'WLDUSDT',
    'XAIUSDT',
    'YGGUSDT',
    'ZECUSDT',
    'ZRXUSDT',
    'ZILUSDT'
];

function acak(array) {
    var currentIndex = array.length, temporaryValue, randomIndex;

    // While there remain elements to shuffle...
    while (0 !== currentIndex) {

        // Pick a remaining element...
        randomIndex = Math.floor(Math.random() * currentIndex);
        currentIndex -= 1;

        // And swap it with the current element.
        temporaryValue = array[currentIndex];
        array[currentIndex] = array[randomIndex];
        array[randomIndex] = temporaryValue;
    }

    return array;
}

function sleep(n) {
    return new Promise(resolve => setTimeout(resolve, n));
}

var tombol = document.createElement('div');
tombol.innerHTML = /*html*/ `
<style>
button.tombol-acak {
    position: fixed;
    top: 80px;
    right: 120px;
    cursor: pointer;
    padding: 5px 10px;
}
</style>
<button class='tombol-acak'>Acak</button>
`;
document.body.appendChild(tombol);

var tombolAcak = document.querySelector('.tombol-acak');
tombolAcak.addEventListener('click', async () => {
    document.querySelector('#header-toolbar-symbol-search').click();
    await sleep(500);
    var pencarian = document.querySelector('[data-role="search"]');
    pencarian.value = acak(listCoin)[0];
});


